# Generated by Django 3.2.9 on 2021-11-29 19:43

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JewelleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Price', models.FloatField()),
                ('Quantity', models.IntegerField()),
                ('about', ckeditor.fields.RichTextField()),
                ('Image1', models.ImageField(height_field=360, upload_to='JewelleryImages', width_field=360)),
                ('Image2', models.ImageField(blank=True, height_field=360, null=True, upload_to='JewelleryImages', width_field=360)),
                ('Image3', models.ImageField(blank=True, height_field=360, null=True, upload_to='JewelleryImages', width_field=360)),
                ('Image4', models.ImageField(blank=True, height_field=360, null=True, upload_to='JewelleryImages', width_field=360)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.jewellerycategory')),
            ],
        ),
    ]
