# Generated by Django 3.2.9 on 2021-11-29 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='Image1',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Image2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Image3',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Image4',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Quantity',
        ),
        migrations.RemoveField(
            model_name='item',
            name='about',
        ),
    ]
