# Generated by Django 3.2.9 on 2021-11-29 20:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20211129_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Image1',
            field=models.ImageField(height_field=360, null=True, upload_to='JewelleryImages', width_field=360),
        ),
        migrations.AddField(
            model_name='item',
            name='Image2',
            field=models.ImageField(blank=True, height_field=360, null=True, upload_to='JewelleryImages', width_field=360),
        ),
        migrations.AddField(
            model_name='item',
            name='Image3',
            field=models.ImageField(blank=True, height_field=360, null=True, upload_to='JewelleryImages', width_field=360),
        ),
        migrations.AddField(
            model_name='item',
            name='Image4',
            field=models.ImageField(blank=True, height_field=360, null=True, upload_to='JewelleryImages', width_field=360),
        ),
        migrations.AddField(
            model_name='item',
            name='Price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='item',
            name='Quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='about',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
