# Generated by Django 3.2.9 on 2021-11-29 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20211129_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='Price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Quantity',
        ),
    ]
