# Generated by Django 3.2.9 on 2021-11-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20211129_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='Image1',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Image2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Image3',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Image4',
        ),
        migrations.AddField(
            model_name='item',
            name='Price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='item',
            name='Quantity',
            field=models.IntegerField(default=0),
        ),
    ]
