# Generated by Django 3.2.9 on 2021-11-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20211129_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Image1',
            field=models.ImageField(height_field='360px', null=True, upload_to='JewelleryImages', width_field='360px'),
        ),
        migrations.AddField(
            model_name='item',
            name='Image2',
            field=models.ImageField(blank=True, height_field='360px', null=True, upload_to='JewelleryImages', width_field='360px'),
        ),
        migrations.AddField(
            model_name='item',
            name='Image3',
            field=models.ImageField(blank=True, height_field='360px', null=True, upload_to='JewelleryImages', width_field='360px'),
        ),
        migrations.AddField(
            model_name='item',
            name='Image4',
            field=models.ImageField(blank=True, height_field='360px', null=True, upload_to='JewelleryImages', width_field='360px'),
        ),
    ]
