# Generated by Django 3.2.9 on 2021-11-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20211129_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Image1',
            field=models.ImageField(null=True, upload_to='JewelleryImages'),
        ),
        migrations.AlterField(
            model_name='item',
            name='Image2',
            field=models.ImageField(blank=True, null=True, upload_to='JewelleryImages'),
        ),
        migrations.AlterField(
            model_name='item',
            name='Image3',
            field=models.ImageField(blank=True, null=True, upload_to='JewelleryImages'),
        ),
        migrations.AlterField(
            model_name='item',
            name='Image4',
            field=models.ImageField(blank=True, null=True, upload_to='JewelleryImages'),
        ),
    ]
