# Generated by Django 3.2.9 on 2022-01-06 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_item_oldprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(default=1)),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.jewellerycategory')),
            ],
        ),
    ]
