# Generated by Django 3.2.9 on 2022-01-06 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.item'),
        ),
    ]
