# Generated by Django 3.2.9 on 2021-11-29 17:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='AboutUs',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='OurMission',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='WhatDoWeDo',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
