# Generated by Django 3.2.9 on 2021-11-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211129_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='Address2',
            field=models.CharField(blank=None, max_length=100, null=None),
        ),
    ]
